Refactoring Scrolling Behaviour (WIP)
zhouhua/obsidian-sticky-headings pull request #23
Opened 2024-08-15 03:55 UTC by zhouhua

2024-08-15 12:35 UTC, itsonlyjames commented
@zhouhua I've simplified the approach for `scrollTo` as well as adding a "Scroll Behaviour" toggle for "auto, smooth, and instant". It's in a sort of working state, it consistently scrolls to the correct spot and because it's not directly at top 0 (probably because of the inline title) it is shown underneath the sticky header. Need to test without inline title. 

Also we need to either add a prettier config or agree upon a code style, my editor defaults to double quotes and is throwing errors all over the place. Perhaps we can setup a prettier config file?

Keen to get your eyes over a few things and see if you can improve the consistency of scrolling to the top most header if at the bottom of the page with smooth scrolling enabled 👍

2024-08-15 12:38 UTC, itsonlyjames commented
I also noticed the issue with the sticky header height not updating was because we called and set it **prior** to it changing, meaning that the reference was old and outdated. If we want to get the correct height, it's probably best to put it in a timeout after we run the scroll function.

2024-08-16 06:52 UTC, zhouhua commented
@itsonlyjames Since CodeMirror-related APIs are not available in preview mode, I’ve decided to refactor the code over the next couple of days and perform some tedious calculations.

2024-08-16 08:30 UTC, itsonlyjames commented
@zhouhua 🤦‍♂️ I did not even consider this when moving into the CodeMirror functionality... that is my bad. 

I'm actually going to investigate using Svelte for handling the rendering elements, it should assist in decoupling the functionality and UI elements. As well as it will allow for better styling and animation/fade in/out transitions. I will investigate this while you refactor the calculations.

2024-08-16 15:49 UTC, zhouhua commented
Check out my latest commit; I've completed the calculation for title scroll top.

Introducing a UI framework is a good idea. Initially, I thought title rendering was relatively simple, so I directly manipulated the DOM. This approach negatively impacts both performance optimization and code readability.

2024-08-16 16:11 UTC, itsonlyjames commented
Checking it out now. 

Have a look at my new branch, I've implemented Svelte and a store so we can simply push `headings.set([])` to render them in there. Will be great. https://github.com/zhouhua/obsidian-sticky-headings/commit/a3f90bde8a0019d2363f698886a608d64395fffc

2024-08-16 16:42 UTC, itsonlyjames requested changes
We're heading in the right direction 🙏
I'll update master prettier file to match yours, and I can look at investigating pushing the headers into my svelte component.

2024-08-16 16:42 UTC, itsonlyjames commented on src/getShownHeadings/source.ts
> +    const { top = 0 } = view.editMode.editor?.coordsAtPos({ line: position.start.line, ch: 0 }, true) || {};
I think using `view.editMode.cm.lineBlockAt(position.start.offset)` will provide a more bulletproof solution as that accounts for elements not currently rendered outside of the viewport, but it does change the way the calculations are done. Depending upon testing it might be okay.

2024-08-16 16:42 UTC, itsonlyjames commented on src/getShownHeadings/source.ts
> +    const { top = 0 } = view.editMode.editor?.coordsAtPos({ line: position.start.line, ch: 0 }, true) || {};
Comes from here: https://discuss.codemirror.net/t/smooth-scroll-to-selection-position/4875/4

2024-08-16 16:42 UTC, itsonlyjames commented on src/getShownHeadings/index.ts
> +  const validHeadings = getValidHeadings(headings, view, stickyHeaderHeight);
This works correctly after the first heading, for some reason I'm getting all returned with offset 0 on first scroll

![Aug-17-2024 02-31-20](https://github.com/user-attachments/assets/b82cadf0-d072-4303-9b70-d16d7106412f)

2024-08-16 16:42 UTC, itsonlyjames commented on src/Plugin.ts
> +            top: offset - stickyContainerHeight,
For the most part, the calculations and everything are working and they're scrolling correctly. However occasionally it'll just shoot off randomly to near the top. See examples. 

![Aug-17-2024 02-37-54](https://github.com/user-attachments/assets/d1f7c3f0-0e32-4e39-bd89-9b412958b688)
![Aug-17-2024 02-38-47](https://github.com/user-attachments/assets/28cb9e87-1149-4514-92f2-a430f45b5338)

2024-08-16 16:42 UTC, itsonlyjames commented on src/Plugin.ts
> +            top: offset - stickyContainerHeight,
I've also provided the culprit issue file in hopes you might be able to replicate: https://pastebin.com/AinG2RL5

2024-08-17 03:15 UTC, zhouhua commented on src/getShownHeadings/source.ts
> +    const { top = 0 } = view.editMode.editor?.coordsAtPos({ line: position.start.line, ch: 0 }, true) || {};
I'm not entirely sure about the exact differences between the two methods. The reason I chose to use `editor.coordsAtPos` is because this method calculates based on the entire editor or window boundaries, including the space for inline title and the properties editor. On the other hand, `cm.lineBlockAt` calculates based on `.cm-contentContainer` boundaries, which do not include the space for inline title and the properties editor.

However, seeing that you have tested and found many cases where the title offset returns as 0, you might be right. `editor.coordsAtPos` might not be reliable in our scenario. I have already switched to using cm.lineBlockAt.

2024-08-17 03:17 UTC, zhouhua commented on src/getShownHeadings/index.ts
> +  const validHeadings = getValidHeadings(headings, view, stickyHeaderHeight);
I haven't encountered this issue before. I've modified the title position calculation as per your suggestion. Let's observe if this resolves the problem.

2024-08-17 03:40 UTC, zhouhua commented on src/Plugin.ts
> +            top: offset - stickyContainerHeight,
I downloaded the file and couldn't reproduce your issue. From your first screenshot, it looks like the cursor's position was targeted. Did you press any keys, or is there a plugin modifying the file's content?

2024-08-17 03:53 UTC, zhouhua commented
I have a favorite Obsidian theme called "Border." It's a bit unique in that the editor doesn't have a background color set, so our plugin appears like this:

![image](https://github.com/user-attachments/assets/077146f4-0656-42dc-b05b-b4136fbcfe0f)

It seems a bit challenging to completely match the title background color with the editor background color.

So I tried changing the style a bit. Do you think this style looks good?

![image](https://github.com/user-attachments/assets/baa690f0-7111-4fbd-898b-6bc53903db54)

2024-08-17 04:20 UTC, itsonlyjames commented on src/Plugin.ts
> +            top: offset - stickyContainerHeight,
I run this all in a test vault that has minimal plugins so as to avoid any conflicts, but I'll chalk it up to an edge-case. I wonder if screen resolution becomes an issue? Maybe it's different on my macbook screen—high-res—compared to my monitor which is 1440p instead. I'll have to test.

2024-08-17 04:23 UTC, itsonlyjames commented
I'm also a big fan of the Border theme. 

I think your implementation looks great! 

If you're happy to, we can get this PR ready to merge and then use my https://github.com/zhouhua/obsidian-sticky-headings/tree/feature/SvelteUI branch to do all the styling. I've completely refactored the entire plugin, however it will make it easier to work with moving forward.

2024-08-17 04:23 UTC, itsonlyjames commented on src/getShownHeadings/index.ts
> +  const validHeadings = getValidHeadings(headings, view, stickyHeaderHeight);
Issue resolved 🙏

2024-08-17 04:24 UTC, itsonlyjames approved these changes

2024-08-17 14:53 UTC, merged